const coachProfileActionTypes = {
  LOAD_COACH_PROFILE_START: 'LOAD_COACH_PROFILE_START',
  LOAD_COACH_PROFILE_END: 'LOAD_COACH_PROFILE_END',
  LOAD_COACH_PROFILE_FAIL: 'LOAD_COACH_PROFILE_FAIL',
  COACH_PROFILE_LOADED: 'COACH_PROFILE_LOADED',
  COACH_FEEDBACKS_LOADED: 'COACH_FEEDBACKS_LOADED'
}

export default coachProfileActionTypes;