const userProfileActionTypes = {
  LOAD_USER_PROFILE_START: 'LOAD_USER_PROFILE_START',
  LOAD_USER_PROFILE_END: 'LOAD_USER_PROFILE_END',
  LOAD_USER_PROFILE_FAIL: 'LOAD_USER_PROFILE_FAIL',
  USER_PROFILE_LOADED: 'USER_PROFILE_LOADED'
}

export default userProfileActionTypes;