const userActionTypes = {
  LOGIN_REQUEST: 'USER_LOGIN_REQUEST',
  LOGIN_SUCESS: 'USER_LOGIN_SUCCESS',
  LOGIN_FAILURE: 'USER_LOGIN_FAILURE',
  FETCH_USER: 'FETCH_USER'
}

export default userActionTypes;